name: macOS Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run dist
      - uses: actions/upload-artifact@v4
        with:
          name: Kay-Y-macOS
          path: |
            dist/*.dmg
            dist/*.zip
